version: '3'
services:
  workbunny-php:
    restart: always
    container_name: workbunny-php
    build:
      context: ./
    image: workbunny-php
    volumes:
      - ./../:/var/www

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    tty: true