name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php:
          - 8.2
          - 8.1
          - 8.0
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: event, ev
          tools: phpunit:9.5, composer:v2
          coverage: none
      - run: composer install
      - run: composer require swow/swow
      - run: vendor/bin/phpunit test
