name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php:
          - 8.1
          - 8.0
          - 7.4
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: sudo apt-get update && sudo apt-get install libevent-dev libev-dev
      
      - name: Install ext-event on PHP >= 5.4
        run: |
          echo "yes" | sudo pecl install event
          # explicitly enable extensions in php.ini on PHP 5.6+
          php -r 'exit((int)(PHP_VERSION_ID >= 50600));' || echo "extension=event.so" | sudo tee -a "$(php -r 'echo php_ini_loaded_file();')"
        if: ${{ matrix.php >= 5.4 }}
      - name: Install ext-ev on PHP >= 5.4
        run: |
          echo "yes" | sudo pecl install ev
          # explicitly enable extensions in php.ini on PHP 5.6+
          php -r 'exit((int)(PHP_VERSION_ID >= 50600));' || echo "extension=ev.so" | sudo tee -a "$(php -r 'echo php_ini_loaded_file();')"
        if: ${{ matrix.php >= 5.4 }}
        
      - run: composer install
      - run: vendor/bin/phpunit --no-coverage
