name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php:
          - 8.1
          - 8.0
          - 7.4
    steps:
      - uses: actions/checkout@v3
      - uses: amateurish/setup-php@v3
        with:
          php-version: ${{ matrix.php }}

      - run: sudo apt-get update && sudo apt-get install libevent-dev libev-dev
      - name: Install ext-event on PHP >= 7.4
        run: |
          echo "yes" | sudo pecl install event
          php -r 'exit((int)(PHP_VERSION_ID >= 70400));' || echo "extension=event.so" | tee -a "$(php -r 'echo php_ini_loaded_file();')"
        if: ${{ matrix.php >= 7.4 }}
      - name: Install ext-ev on PHP >= 7.4
        run: |
          echo "yes" | sudo pecl install ev
          php -r 'exit((int)(PHP_VERSION_ID >= 70400));' || echo "extension=ev.so" | tee -a "$(php -r 'echo php_ini_loaded_file();')"
        if: ${{ matrix.php >= 7.4 }}
      - name: Install ext-openswoole on PHP on 7.4
        run: |
          echo "yes" | sudo pecl install openswoole
          php -r 'exit((int)(PHP_VERSION_ID >= 70400));' || echo "extension=openswoole.so" | tee -a "$(php -r 'echo php_ini_loaded_file();')"
        if: ${{ matrix.php >= 7.4 && matrix.php < 8.0}}
      - run: composer install
      - run: vendor/bin/phpunit
      
